# Alimenta tabela de Cursos
# select id, codigo, nome, nome_reduzido, tempo_minimo, tempo_maximo, data_inicio, data_fim, unidade_organizacional_id as dept from curso order by 1;      
=begin
select '{:code => \''||codigo||'\', :name => \''||curso.nome||'\', :nickname => \''||nome_reduzido||'\', :goal => \''||finalidade||'\',  :mintime => \''||tempo_minimo||'\', :maxtime => \''||tempo_maximo||'\', :started_at => \''||curso.data_inicio||'\', :ended_at => \''||curso.data_fim||'\', :dept => Dept.find_by_name(\''||elemento_organizacional.nome||'\')},' from curso, elemento_organizacional where curso.unidade_organizacional_id = elemento_organizacional.id order by 1;


-- comando shell
psql -U postgres -h localhost -d dbsiga-edu -c "" > cursos.txt


psql -U postgres -h localhost -d dbsiga-edu -c "select '{:code => \''||codigo||'\', :name => \''||curso.nome||'\', :nickname => \''||nome_reduzido||'\', :goal => \''||finalidade||'\',  :mintime => \''||tempo_minimo||'\', :maxtime => \''||tempo_maximo||'\', :started_at => \''||curso.data_inicio||'\', :ended_at => \''||curso.data_fim||'\', :dept => Dept.find_by_name(\''||elemento_organizacional.nome||'\')},' from curso, elemento_organizacional where curso.unidade_organizacional_id = elemento_organizacional.id order by 1;" > cursos.txt
=end
Course.delete_all
ActiveRecord::Migration.execute("SELECT SETVAL('courses_id_seq', 1, false);")
courses = Course.create([
  {:code => '002', :name => 'Agente ambiental', :nickname => 'Agente ambiental', :goal => 'Capacitar profissionais para atuar com a educação ambiental em unidades de conservação e/ou preservação ambiental - escolas, ONGs, e demais órgãos.',  :mintime => '3', :maxtime => '3', :started_at => '2010-05-31', :ended_at => '2010-09-10', :dept => Dept.find_by_name('Diretoria de Ensino, Pesquisa e Extensão CSAM')},
   {:code => '003', :name => 'Vendas e Pós-Venda', :nickname => 'Vendas e Pós-Venda', :goal => 'Formar Profissionais para o Mundo do Trabalho',  :mintime => '120', :maxtime => '160', :started_at => '2010-03-15', :ended_at => '2010-06-16', :dept => Dept.find_by_name('Diretoria de Ensino, Pesquisa e Extensão CBRA')},
   {:code => '006', :name => 'Operador Básico de Microcomputador: Digitação, Linux e Broffice', :nickname => 'Op. de Micro', :goal => 'Capacitar Pessoas para operar microcomputadores',  :mintime => '106', :maxtime => '106', :started_at => '2010-05-24', :ended_at => '2010-07-08', :dept => Dept.find_by_name('Diretoria de Ensino, Pesquisa e Extensão CTAG')},
   {:code => '008', :name => 'Técnico em Eventos - modalidade concomitante', :nickname => 'Técnico em Eventos', :goal => 'Formar técnicos em eventos',  :mintime => '2', :maxtime => '3', :started_at => '2009-08-12', :ended_at => '2009-09-15', :dept => Dept.find_by_name('Diretoria de Ensino, Pesquisa e Extensão CBRA')},
   {:code => '013', :name => 'TÉCNICO EM RECICLAGEM', :nickname => 'TEC. RECICLAGEM', :goal => 'são suprir a carência de mão-de-obra especializada nas diversas áreas do conhecimento, promover a educação profissional de qualidade nos diversos níveis e proporcionar o desenvolvimento regional.',  :mintime => '4', :maxtime => '8', :started_at => '2010-08-02', :ended_at => '2012-07-06', :dept => Dept.find_by_name('Diretoria de Ensino, Pesquisa e Extensão CSAM')},
   {:code => '014', :name => 'Projeto, Montagem e Manutenção de Móveis', :nickname => 'Projeto, Montagem e Manutenção de Móveis', :goal => 'Qualificar profissionais na área de móveis.',  :mintime => '3', :maxtime => '3', :started_at => '2010-09-13', :ended_at => '2010-12-17', :dept => Dept.find_by_name('Diretoria de Ensino, Pesquisa e Extensão CSAM')},
   {:code => '015', :name => 'Auxiliar de Mecânica a Diesel', :nickname => 'FIC de Mecânica a Diesel', :goal => 'Capacitar profissionais na área de Mecânica.',  :mintime => '3', :maxtime => '3', :started_at => '2010-09-13', :ended_at => '2010-12-17', :dept => Dept.find_by_name('Diretoria de Ensino, Pesquisa e Extensão CSAM')},
   {:code => '017', :name => 'Agente Ambiental', :nickname => 'Fic_Agente Ambiental', :goal => 'Capacitar profissinais para atuar na área ambiental.',  :mintime => '3', :maxtime => '3', :started_at => '2010-09-13', :ended_at => '2010-12-17', :dept => Dept.find_by_name('Diretoria de Ensino, Pesquisa e Extensão CSAM')},
   {:code => '018', :name => 'Língua Espanhola Nível Básico', :nickname => 'Língua Espanhola Nível Básico', :goal => 'Capacitar profissionais para atuar com estrangeiros em língua espanhola',  :mintime => '3', :maxtime => '3', :started_at => '2010-09-13', :ended_at => '2010-12-17', :dept => Dept.find_by_name('Diretoria de Ensino, Pesquisa e Extensão CSAM')},
   {:code => '019', :name => 'Almoxarife e Apontador', :nickname => 'FIC_Almoxarife e Apontador', :goal => 'Capacitar profissionais para atuarem na área de almoxarife e apontador.',  :mintime => '3', :maxtime => '3', :started_at => '2010-09-13', :ended_at => '2010-12-17', :dept => Dept.find_by_name('Diretoria de Ensino, Pesquisa e Extensão CSAM')},
   {:code => '020', :name => 'Operador Básico de Computador', :nickname => 'FIC_Operador Básico de Computador', :goal => 'Capacitar para utilização do computador.',  :mintime => '3', :maxtime => '3', :started_at => '2010-09-13', :ended_at => '2010-12-17', :dept => Dept.find_by_name('Diretoria de Ensino, Pesquisa e Extensão CSAM')},
   {:code => '023', :name => 'Introdução ao Gerenciamento Ambiental', :nickname => 'Gerenciamento Ambiental', :goal => 'Despertar no grupo a importância do conceito de desenvolvimento sustentável como um campo do conhecimento transdisciplinar e global.',  :mintime => '1', :maxtime => '1', :started_at => '2010-10-13', :ended_at => '2010-12-08', :dept => Dept.find_by_name('Diretoria de Ensino, Pesquisa e Extensão CBRA')},
   {:code => '024', :name => 'Atendimento e Vendas', :nickname => 'Atendimento e vendas', :goal => 'Atualizar',  :mintime => '3', :maxtime => '3', :started_at => '2010-11-01', :ended_at => '2011-02-01', :dept => Dept.find_by_name('Diretoria de Ensino, Pesquisa e Extensão CGAM')},
   {:code => '025', :name => 'Atendente de Farmácias e Drogarias', :nickname => 'Atendente de Farmácias e Drogarias', :goal => 'Atualizar',  :mintime => '3', :maxtime => '3', :started_at => '2010-11-01', :ended_at => '2011-02-01', :dept => Dept.find_by_name('Diretoria de Ensino, Pesquisa e Extensão CGAM')},
   {:code => '026', :name => 'Cerimonial e Protocolo', :nickname => 'CP', :goal => 'Capacitar o aluno para o conhecimento das competências necessárias à prática do Cerimonial e Protocolo de Eventos. Esse profissional poderá auxiliar na realização dos diversos tipos de eventos. ',  :mintime => '1', :maxtime => '1', :started_at => '2010-10-07', :ended_at => '2010-12-15', :dept => Dept.find_by_name('Diretoria de Ensino, Pesquisa e Extensão CBRA')},
   {:code => '033', :name => 'Reforma Ortográfica', :nickname => 'Refort', :goal => ' Levar a conhecimento o texto da nova Reforma Ortográfica sob uma perspectiva teórico-prática, conforme o Acordo promulgado pelo Decreto n. 6.583, de 29 de setembro de 2008, enfatizando as mudanças ',  :mintime => '8', :maxtime => '8', :started_at => '2011-03-14', :ended_at => '2011-03-21', :dept => Dept.find_by_name('Diretoria de Ensino, Pesquisa e Extensão CSAM')},
   {:code => '037', :name => 'Aprendiz de Mecânica de Manutenção', :nickname => 'Aprendiz Mec_FIC', :goal => 'Formar aprendizes de mecânica de manutenção e preprarar para o curso técnico de Eletromecânica.',  :mintime => '216', :maxtime => '216', :started_at => '2011-09-05', :ended_at => '2011-12-20', :dept => Dept.find_by_name('Diretoria de Ensino, Pesquisa e Extensão CTAG')},
   {:code => '038', :name => 'Recepção hoteleira', :nickname => 'RH', :goal => 'Capacitar o aluno para o conhecimento das competências necessárias à supervisão e recepção hoteleira. Esse profissional poderá auxiliar no recebimento de hóspedes, organograma e funções da portaria,',  :mintime => '90', :maxtime => '90', :started_at => '2011-04-25', :ended_at => '2011-07-07', :dept => Dept.find_by_name('Diretoria de Ensino, Pesquisa e Extensão CBRA')},
   {:code => '040', :name => 'Língua Inglesa', :nickname => 'Inglês', :goal => 'Comunicar-se em nível elementar através da leitura , escrita, compreensão auditiva e produção oral',  :mintime => '6', :maxtime => '6', :started_at => '2011-04-04', :ended_at => '2011-06-27', :dept => Dept.find_by_name('Diretoria de Ensino, Pesquisa e Extensão CSAM')},
   {:code => '044', :name => 'FIC Padeiro e Confeiteiro', :nickname => 'FIC Padeiro e Confeiteiro', :goal => 'Capacitar pessoas em panificação.',  :mintime => '1', :maxtime => '1', :started_at => '2011-09-26', :ended_at => '2011-12-23', :dept => Dept.find_by_name('Diretoria de Ensino, Pesquisa e Extensão CRF')},
   {:code => '046', :name => 'Auxiliar Administrativo', :nickname => 'Aux Adm', :goal => 'O curso tem por objetivo capacitar pessoas para atuar como auxiliar administrativo em organizações, apresentando um conjunto de conhecimentos necessários para a execução das atividades.',  :mintime => '90', :maxtime => '90', :started_at => '2011-10-10', :ended_at => '2011-12-16', :dept => Dept.find_by_name('Diretoria de Ensino, Pesquisa e Extensão CSSB')},
   {:code => '054', :name => 'Técnico em Eletromecânica', :nickname => 'Eletromecânica', :goal => 'Tem por objetivo formar profissionais capazes de atuar, sob a supervisão\r
   de engenheiros, no projeto e execução de instalações elétricas e mecânicas de\r
   equipamentos industriais.',  :mintime => '1', :maxtime => '1', :started_at => '2011-08-15', :ended_at => '2011-12-20', :dept => Dept.find_by_name('Diretoria de Ensino, Pesquisa e Extensão CTAG')},
   {:code => '055', :name => 'Formação Básica de Tradutores/interpretes de Língua Brasileira de Sinais ', :nickname => 'LIBRAS - ', :goal => 'Estimular o processo de ensino – aprendizagem dos ouvintes para auxiliá-los a adquirir uma formação mais inclusiva.',  :mintime => '3', :maxtime => '3', :started_at => '2011-10-24', :ended_at => '2012-06-20', :dept => Dept.find_by_name('Diretoria de Ensino, Pesquisa e Extensão CTAG')},
   {:code => '056', :name => 'FIC - OPERADOR DE MICROCOMPUTADOR', :nickname => 'CBRA FIC OP MICRO', :goal => 'Cumprir as atividades previstas no projeto de extensão Inclusão Digital para trabalhadores de Brasília.',  :mintime => '1', :maxtime => '1', :started_at => '2011-08-11', :ended_at => '2011-12-15', :dept => Dept.find_by_name('Diretoria de Ensino, Pesquisa e Extensão CBRA')},
   {:code => '060', :name => 'Técnico em Transações Imobiliárias - CRF', :nickname => 'Téc. em Transações Imobiliárias - CRF', :goal => 'Oferecer conhecimento prático e teórico nas atividades de Transações Imobiliárias, para viabilizar condições para que o estudante desenvolva as competências e habilidades profissionais.',  :mintime => '320', :maxtime => '320', :started_at => '2012-02-13', :ended_at => '2013-07-31', :dept => Dept.find_by_name('Diretoria de Ensino, Pesquisa e Extensão CRF')},
   {:code => '061', :name => 'Secretariado Escolar', :nickname => 'Sec Esc', :goal => 'O curso tem por objetivo, desenvolver os fundamentos técnicos e científicos da qualificação profissional, para que atue nas secretarias de instituições educacionais públicas ou privadas.',  :mintime => '90', :maxtime => '90', :started_at => '2011-10-10', :ended_at => '2011-12-16', :dept => Dept.find_by_name('Diretoria de Ensino, Pesquisa e Extensão CSSB')},
   {:code => '062', :name => 'Espanhol Básico', :nickname => 'Esp', :goal => 'Desenvolver a capacidade de comunicação na língua estrangeira em seu nível incipiente, possibilitando uma compreensão geral do funcionamento da língua e a comunicação em seu sentido mais imediato.',  :mintime => '90', :maxtime => '90', :started_at => '2011-10-10', :ended_at => '2011-12-16', :dept => Dept.find_by_name('Diretoria de Ensino, Pesquisa e Extensão CSSB')},
   {:code => '063', :name => 'Inglês Básico', :nickname => 'ING', :goal => 'Desenvolver a capacidade de comunicação na língua estrangeira em seu nível incipiente, possibilitando uma compreensão geral do funcionamento da língua e a comunicação em seu sentido mais imediato.',  :mintime => '90', :maxtime => '90', :started_at => '2011-10-10', :ended_at => '2011-12-16', :dept => Dept.find_by_name('Diretoria de Ensino, Pesquisa e Extensão CSSB')},
   {:code => '064', :name => 'CURSO PREPARATÓRIO PARA CERTIFICAÇÃO', :nickname => 'HCDA', :goal => 'Preparar profissionais na área de Informática com ênfase em Redes de Computadores para o mercado de trabalho.',  :mintime => '1', :maxtime => '1', :started_at => '2011-10-22', :ended_at => '2012-06-30', :dept => Dept.find_by_name('Diretoria de Ensino, Pesquisa e Extensão CTAG')},
   {:code => '065', :name => 'FIC Empreendedorismo e Gestão em A&B', :nickname => 'FIC A&B', :goal => '',  :mintime => '1', :maxtime => '1', :started_at => '2012-03-26', :ended_at => '2012-07-31', :dept => Dept.find_by_name('Diretoria de Ensino, Pesquisa e Extensão CRF')},
   {:code => '067', :name => 'Línux Básico Para Deficientes Visuais', :nickname => 'Linux Básico Def Visu', :goal => 'Estimular o processo de ensino – aprendizagem dos deficientes visuais de um software, ferramenta livre acessível e compatível com todas as arquiteturas de computadores disponíveis no mercado, amplia',  :mintime => '40', :maxtime => '40', :started_at => '2012-01-09', :ended_at => '2012-01-31', :dept => Dept.find_by_name('Diretoria de Ensino, Pesquisa e Extensão CSSB')},
   {:code => '077', :name => 'FIC Padeiro e Confeiteiro - CRF', :nickname => 'FIC P&C 1/2012', :goal => 'Tornar o cidadão apto a elaborar e servir produtos de panificação e confeitaria, considerando os aspectos higiênico-sanitários, a responsabilidade profissional, socioeconômica e ambiental.',  :mintime => '6', :maxtime => '6', :started_at => '2012-03-26', :ended_at => '2012-08-30', :dept => Dept.find_by_name('Diretoria de Ensino, Pesquisa e Extensão CRF')},
   {:code => '079', :name => 'FIC Espanhol para iniciantes', :nickname => 'Espanhol', :goal => '',  :mintime => '60', :maxtime => '60', :started_at => '2012-01-17', :ended_at => '2012-01-17', :dept => Dept.find_by_name('Diretoria de Ensino, Pesquisa e Extensão CBRA')},
   {:code => '087', :name => 'FIC Espanhol para Copa', :nickname => 'FIC ESPANHOL COPA', :goal => 'Alterar',  :mintime => '100', :maxtime => '110', :started_at => '2012-03-26', :ended_at => '2012-12-12', :dept => Dept.find_by_name('Diretoria de Ensino, Pesquisa e Extensão CBRA')}, 
   {:code => '088', :name => 'Teste Técnico subsequente', :nickname => 'Teste Técnico subsequente', :goal => 'Teste Técnico subsequente',  :mintime => '3', :maxtime => '5', :started_at => '2012-01-01', :ended_at => '2013-07-01', :dept => Dept.find_by_name('Diretoria de Ensino, Pesquisa e Extensão CBRA')},
    {:code => '089', :name => 'FIC Francês para a Copa', :nickname => 'FIC Francês Copa', :goal => '',  :mintime => '100', :maxtime => '100', :started_at => '2012-03-26', :ended_at => '2012-07-31', :dept => Dept.find_by_name('Diretoria de Ensino, Pesquisa e Extensão CBRA')},
    {:code => '091', :name => 'Técnico em Transações Imobiliárias', :nickname => 'TTI', :goal => 'O curso Técnico em Transações Imobiliárias tem como objetivo principal capacitar os profissionais que já estão no mercado e os que nele pretendem se inserir, oferecendo prática aliana à teoria.',  :mintime => '1', :maxtime => '3', :started_at => '2012-02-13', :ended_at => '2013-07-31', :dept => Dept.find_by_name('Diretoria de Ensino, Pesquisa e Extensão CRF')},
    {:code => '092', :name => 'Técnico em Cozinha', :nickname => 'TCZ', :goal => 'O curso Técnico em Cozinha, como apresentado nessa proposta, tem como objetivo principal, capacitar os profissionais que já estão no mercado e os que nele pretendem se inserir.',  :mintime => '1', :maxtime => '3', :started_at => '2012-07-30', :ended_at => '2013-12-20', :dept => Dept.find_by_name('Diretoria de Ensino, Pesquisa e Extensão CRF')},
    {:code => '093', :name => 'Atendimento ao Cliente - Setor Automotivo', :nickname => 'Atendimento ao Cliente - Setor Automotivo', :goal => 'Contribuir para a compreensão dos aspectos necessários para a qualificação profissional relacionada a atendimento às necessidades dos clientes do setor automotivo.',  :mintime => '120', :maxtime => '180', :started_at => '2012-03-20', :ended_at => '2012-07-27', :dept => Dept.find_by_name('Diretoria de Ensino, Pesquisa e Extensão CEST')},
    {:code => '097', :name => 'Auxiliar administrativo', :nickname => 'AuxAdm', :goal => 'capacitar pessoas para atuar como auxiliar administrativo em organizações, apresentando um conjunto de conhecimentos necessários para a execução das atividades e procedimentos administrativos.',  :mintime => '90', :maxtime => '90', :started_at => '2011-04-25', :ended_at => '2011-07-07', :dept => Dept.find_by_name('Diretoria de Ensino, Pesquisa e Extensão CBRA')},
    {:code => '098', :name => 'Técnico em Vestuário', :nickname => 'Vestuário', :goal => 'Formar profissionais empreendedores, capazes de desenvolver atividades ou funções típicas da área, segundo os padrões de qualidade e produtividade requeridos pela natureza do trabalho do técnico.',  :mintime => '4', :maxtime => '6', :started_at => '2011-08-15', :ended_at => '2011-12-20', :dept => Dept.find_by_name('Diretoria de Ensino, Pesquisa e Extensão CTAG')},
    {:code => '100', :name => 'FIC Inglês', :nickname => 'FIC Inglês', :goal => 'Capacitação em Inglês',  :mintime => '4', :maxtime => '6', :started_at => '2011-09-26', :ended_at => '2011-12-23', :dept => Dept.find_by_name('Diretoria de Ensino, Pesquisa e Extensão CRF')}, 
])
